# API Linter Configuration
# https://linter.aip.dev/

- included_paths:
    - "**/*.proto"
  disabled_rules:
    - "core::0140::abbreviations"
    - "core::0191::java-multiple-files"
    - "core::0191::java-outer-classname"
    - "core::0191::java-package"
    - "core::0123::resource-annotation"
    - "core::0203::optional"
    - "core::0203::required"
    - "core::0127::http-annotation"
    - "core::0131::request-message-name"
    - "core::0132::response-message-name"
    - "core::0158::request-required-fields"
    - "core::0203::input-only"
    - "core::0203::output-only"
    - "core::0203::immutable"
