// Original file: ../specification/grpc/a2a.proto


/**
 * --8<-- [start:HTTPAuthSecurityScheme]
 */
export interface HTTPAuthSecurityScheme {
  /**
   * Description of this security scheme.
   */
  'description'?: (string);
  /**
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   */
  'scheme'?: (string);
  /**
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   */
  'bearer_format'?: (string);
}

/**
 * --8<-- [start:HTTPAuthSecurityScheme]
 */
export interface HTTPAuthSecurityScheme__Output {
  /**
   * Description of this security scheme.
   */
  'description': (string);
  /**
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   */
  'scheme': (string);
  /**
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   */
  'bearer_format': (string);
}
