// Original file: ../specification/grpc/a2a.proto

import type { TaskStatus as _a2a_v1_TaskStatus, TaskStatus__Output as _a2a_v1_TaskStatus__Output } from '../../a2a/v1/TaskStatus';
import type { Artifact as _a2a_v1_Artifact, Artifact__Output as _a2a_v1_Artifact__Output } from '../../a2a/v1/Artifact';
import type { Message as _a2a_v1_Message, Message__Output as _a2a_v1_Message__Output } from '../../a2a/v1/Message';
import type { Struct as _google_protobuf_Struct, Struct__Output as _google_protobuf_Struct__Output } from '../../google/protobuf/Struct';

/**
 * --8<-- [start:Task]
 * Task is the core unit of action for A2A. It has a current status
 * and when results are created for the task they are stored in the
 * artifact. If there are multiple turns for a task, these are stored in
 * history.
 */
export interface Task {
  /**
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   */
  'id'?: (string);
  /**
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages). Created by the A2A server.
   */
  'context_id'?: (string);
  /**
   * The current status of a Task, including state and a message.
   */
  'status'?: (_a2a_v1_TaskStatus | null);
  /**
   * A set of output artifacts for a Task.
   */
  'artifacts'?: (_a2a_v1_Artifact)[];
  /**
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   */
  'history'?: (_a2a_v1_Message)[];
  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   */
  'metadata'?: (_google_protobuf_Struct | null);
}

/**
 * --8<-- [start:Task]
 * Task is the core unit of action for A2A. It has a current status
 * and when results are created for the task they are stored in the
 * artifact. If there are multiple turns for a task, these are stored in
 * history.
 */
export interface Task__Output {
  /**
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   */
  'id': (string);
  /**
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages). Created by the A2A server.
   */
  'context_id': (string);
  /**
   * The current status of a Task, including state and a message.
   */
  'status': (_a2a_v1_TaskStatus__Output | null);
  /**
   * A set of output artifacts for a Task.
   */
  'artifacts': (_a2a_v1_Artifact__Output)[];
  /**
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   */
  'history': (_a2a_v1_Message__Output)[];
  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   */
  'metadata': (_google_protobuf_Struct__Output | null);
}
