// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: a2a_jsonrpc.proto

/* eslint-disable */
import {
  AgentCard,
  CancelTaskRequest,
  CreateTaskPushNotificationConfigRequest,
  DeleteTaskPushNotificationConfigRequest,
  GetAgentCardRequest,
  GetTaskPushNotificationConfigRequest,
  GetTaskRequest,
  ListTaskPushNotificationConfigRequest,
  ListTaskPushNotificationConfigResponse,
  SendMessageRequest,
  SendMessageResponse,
  Task,
  TaskPushNotificationConfig,
  TaskSubscriptionRequest,
} from "./a2a_core";

export const protobufPackage = "a2a.v1";

/** Older protoc compilers don't understand edition yet. */

export enum JSONRPCErrorCode {
  JSON_RPC_ERROR_CODE_UNSPECIFIED = "JSON_RPC_ERROR_CODE_UNSPECIFIED",
  PARSE_ERROR = "PARSE_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  METHOD_NOT_FOUND = "METHOD_NOT_FOUND",
  INVALID_PARAMS = "INVALID_PARAMS",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_NOT_CACHEABLE = "TASK_NOT_CACHEABLE",
  PUSH_NOTIFICATION_NOT_SUPPORTED = "PUSH_NOTIFICATION_NOT_SUPPORTED",
  UNSUPPORTED_OPERATION_ERROR = "UNSUPPORTED_OPERATION_ERROR",
  CONTENT_TYPE_NOT_SUPPORTED = "CONTENT_TYPE_NOT_SUPPORTED",
  INVALID_AGENT_RESPONSE = "INVALID_AGENT_RESPONSE",
  AUTHENTICATED_CARD_NOT_CONFIGURED = "AUTHENTICATED_CARD_NOT_CONFIGURED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** A2AJsonRPCRequest represents a JSON-RPC request for the A2A protocol. */
export interface JSONRPCRequest {
  /** The JSON-RPC version, must be "2.0". */
  jsonrpc: string;
  /** The method to be invoked. */
  method: string;
  /** The identifier for this request. */
  id?:
    | { $case: "idString"; value: string }
    | { $case: "idInt"; value: number }
    | undefined;
  /** The parameters for the method. */
  params?:
    | { $case: "sendMessageRequest"; value: SendMessageRequest }
    | { $case: "getTaskRequest"; value: GetTaskRequest }
    | { $case: "cancelTaskRequest"; value: CancelTaskRequest }
    | { $case: "taskSubscriptionRequest"; value: TaskSubscriptionRequest }
    | { $case: "createTaskPushNotificationConfigRequest"; value: CreateTaskPushNotificationConfigRequest }
    | { $case: "getTaskPushNotificationConfigRequest"; value: GetTaskPushNotificationConfigRequest }
    | { $case: "listTaskPushNotificationConfigRequest"; value: ListTaskPushNotificationConfigRequest }
    | { $case: "deleteTaskPushNotificationConfigRequest"; value: DeleteTaskPushNotificationConfigRequest }
    | { $case: "getAgentCardRequest"; value: GetAgentCardRequest }
    | undefined;
}

export interface JSONRPCResponse {
  response?:
    | { $case: "success"; value: JSONRPCSuccessResponse }
    | { $case: "error"; value: JSONRPCErrorResponse }
    | undefined;
}

export interface JSONRPCSuccessResponse {
  jsonrpc: string;
  id?: { $case: "idString"; value: string } | { $case: "idInt"; value: number } | undefined;
  result?:
    | { $case: "sendMessageResponse"; value: SendMessageResponse }
    | { $case: "getTaskResponse"; value: Task }
    | { $case: "cancelTaskResponse"; value: Task }
    | { $case: "listTaskPushNotificationConfigResponse"; value: ListTaskPushNotificationConfigResponse }
    | { $case: "getTaskPushNotificationConfigResponse"; value: TaskPushNotificationConfig }
    | { $case: "createTaskPushNotificationConfigResponse"; value: TaskPushNotificationConfig }
    | { $case: "getAgentCardResponse"; value: AgentCard }
    | undefined;
}

export interface JSONRPCErrorResponse {
  jsonrpc: string;
  id?: { $case: "idString"; value: string } | { $case: "idInt"; value: number } | undefined;
  error: JSONRPCError | undefined;
}

export interface JSONRPCError {
  code: JSONRPCErrorCode;
  message: string;
  data: { [key: string]: any } | undefined;
}
