// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: a2a_grpc.proto

/* eslint-disable */

export const protobufPackage = "a2a.v1";

/** Older protoc compilers don't understand edition yet. */
