# API Linter Configuration
# https://linter.aip.dev/

# Disable rules related to blank lines and formatting
disabled_rules:
  # Formatting and blank line rules
  - core::0191::java-multiple-files
  - core::0191::java-outer-classname
  - core::0191::java-package

  # Comment and documentation rules
  - core::0192::has-comments # Suppress missing comment warnings
  - core::0123::resource-annotation # Resource name annotations
  - core::0203::optional # Optional field comments
  - core::0203::required # Required field comments
  - core::0127::http-annotation # HTTP annotation comments
  - core::0131::request-message-name # Request naming
  - core::0132::response-message-name # Response naming
  - core::0158::request-required-fields # Required request fields
  - core::0203::input-only # Input only field comments
  - core::0203::output-only # Output only field comments
  - core::0203::immutable # Immutable field comments

# You can also use include_rules to be more specific
# enabled_rules:
#   - all

# Set the minimum severity level to report
# Options: disabled, info, warning, error
# severity: warning
