# A2A repo: .github/workflows/dispatch-a2a-json-update.yml
name: Dispatch A2A JSON Update

on:
  push:
    branches:
      - main
    paths:
      - "specification/**/*"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get JSON-escaped commit message
        id: commit_message_escape
        run: |
          # Use jq to properly JSON-escape the multi-line commit message.
          ESCAPED_MESSAGE=$(echo "$COMMIT_MESSAGE" | jq -R .)
          echo "message=$ESCAPED_MESSAGE" >> "$GITHUB_OUTPUT"
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Dispatch repository_dispatch to a2a-python
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.A2A_BOT_PAT }}
          repository: a2aproject/a2a-python
          event-type: a2a_json_update
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "message": ${{ steps.commit_message_escape.outputs.message }}
            }
