name: Check Spelling

on:
  pull_request:
    branches:
      - '**'
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'
  issue_comment:
    types:
      - 'created'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    # if on repo to avoid failing runs on forks
    if: |
      github.repository == 'google-a2a/A2A'
        && (contains(github.event_name, 'pull_request') || github.event_name == 'push')
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: false
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@main
        with:
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
          # Assuming 's' was meant to be a dictionary source configuration
          # You might need to adjust this based on the actual action documentation
          config: |
            {"cspell": "https://raw.githubusercontent.com/streetsidesoftware/cspell-dicts/main/dictionaries/"}
          check_file_names: true # Use boolean true/false or '1' if action expects string/number
          spell_check_this: check-spelling/spell-check-this@main
          post_comment: false # Use boolean true/false or '0' if action expects string/number
          use_magic_file: true # Use boolean true/false or '1' if action expects string/number
          report-timing: true # Use boolean true/false or '1' if action expects string/number
          warnings: bad-regex,binary-file,deprecated-feature,ignored-expect-variant,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check,unclosed-block-ignore-begin,unclosed-block-ignore-end
          experimental_apply_changes_via_bot: true # Use boolean true/false or '1' if action expects string/number
          # dictionary_source_prefix was likely part of the config or another parameter
          # Removing it as a separate key based on the incorrect structure
          extra_dictionaries: |
            cspell:custom/custom-words.txt
            cspell:aws/dict/aws.txt
            cspell:bash/samples/bash-words.txt
            cspell:companies/dict/companies.txt
            cspell:css/dict/css.txt
            cspell:data-science/dict/data-science-models.txt
            cspell:data-science/dict/data-science.txt
            cspell:data-science/dict/data-science-tools.txt
            cspell:en_shared/dict/acronyms.txt
            cspell:en_shared/dict/shared-additional-words.txt
            cspell:en_GB/en_GB.trie
            cspell:en_US/en_US.trie
            cspell:filetypes/src/filetypes.txt
            cspell:fonts/dict/fonts.txt
            cspell:fullstack/dict/fullstack.txt
            cspell:golang/dict/go.txt
            cspell:google/dict/google.txt
            cspell:html/dict/html.txt
            cspell:java/src/java.txt
            cspell:k8s/dict/k8s.txt
            cspell:mnemonics/dict/mnemonics.txt
            cspell:monkeyc/src/monkeyc_keywords.txt
            cspell:node/dict/node.txt
            cspell:npm/dict/npm.txt
            cspell:people-names/dict/people-names.txt
            cspell:python/dict/python.txt
            cspell:python/dict/python-common.txt
            cspell:shell/dict/shell-all-words.txt
            cspell:software-terms/dict/softwareTerms.txt
            cspell:software-terms/dict/webServices.txt
            cspell:sql/src/common-terms.txt
            cspell:sql/src/sql.txt
            cspell:sql/src/tsql.txt
            cspell:terraform/dict/terraform.txt
            cspell:typescript/dict/typescript.txt
          # Check if check_extra_dictionaries should contain a list or a single value
          # Based on the original, it might expect a list, or the string value
          check_extra_dictionaries: |
            cspell:custom/custom-words.txt
          only_check_changed_files: true # Use boolean true/false or '1' if action expects string/number
          longest_word: '10' # Keep as string if action expects string